baseURL: "https://bibimpen.netlify.app"
languageCode: en-us
title: BibimPen Blog
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to **Bibimpen**, my personal blog where I share my thoughts and experiences on a variety of topics. Whether you're here to read about travel, food, culture, or just to learn a little more about me, I'm so glad you're here.I started Bibimpen as a way to document my adventures and connect with others who share my interests. I hope that through my writing, I can inspire you to explore new places, try new things, and find joy in the little moments of life.So grab a cup of tea (or coffee, if that's your thing) and settle in. I can't wait to share my stories with you, and I hope you'll share yours with me too.Thank you for stopping by, and I hope you'll come back soon!
  socialIcons:
        - name: facebook
          url: "https://facebook.com/"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true  
  
  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true



menu:
      main:
        - identifier: search
          name: search
          url: search
          weight: 20
        - identifier: home
          name: home
          url: /
          weight: 2
        - identifier: posts
          name: blog
          url: /posts/
          weight: 3
        - identifier: tags
          name: tags
          url: /tags/
          weight: 15
        - identifier: archives
          name: archives
          url: /archives/
          weight: 20
        - identifier: categories
          name: categories
          url: /categories/
          weight: 20
                  
        