baseURL: "https://bibimpen.netlify.app"
languageCode: en-us
title: BibimPen Blog
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: "Thank you for visiting my blog! We're currently working hard to bring you the best content possible. Please check back soon for updates and new posts. In the meantime, feel free to explore our social media pages and stay connected with us. Thank you for your patience and support!"
  socialIcons:
        - name: facebook
          url: "https://facebook.com/"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true  
  
  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true



menu:
      main:
        - identifier: search
          name: search
          url: search
          weight: 20
        - identifier: home
          name: home
          url: /
          weight: 2
        - identifier: posts
          name: blog
          url: /posts/
          weight: 3
        - identifier: tags
          name: tags
          url: /tags/
          weight: 15
        - identifier: archives
          name: archives
          url: /archives/
          weight: 20
        - identifier: categories
          name: categories
          url: /categories/
          weight: 20
                  
        